# Generated by Django 3.2.6 on 2021-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(choices=[('Dinner', 'Dinner'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomtype',
            field=models.CharField(choices=[('NonAC', 'NonAC'), ('Suite', 'Suite'), ('Deluxe', 'Deluxe'), ('AC', 'AC')], max_length=6),
        ),
        migrations.AlterField(
            model_name='table',
            name='tablenum',
            field=models.IntegerField(),
        ),
    ]
